In [ ]:
#missing value

import pandas as pd
import numpy as np

df = pd.read_csv(r'xxx')
df.dropna(inplace=True)  #inplace=True คือให้แทนที่ผลลัพธ์ในออบเจ็กต์เดิม

In [ ]:
#missing value (fillna-1)

v_mean = df['volume'].mean()
df['volume'].fillna(v_mean, inplace=True)
df['weight'].fillna(df['weight'].mean(), inplace=True)


In [ ]:
#missing value (fillna-2)

df['volume'].fillna(method='ffill', inplace=True) # Takes the value from the previous non-null cell and fills it with the next cell that contains the null
df['weight'].fillna(method='bfill', inplace=True)  # Takes the value from the nerxt non-null cell and fills it with the previous cell that contains the null

In [ ]:
#label encoder 

from sklearn.preprocessing import LabelEncoder

data = ['Apple', 'Mango', 'Grape', 'Durian', 'Mango', 'Grape']
encoder = LabelEncoder()

encoder.fit(data)

enc_data1 = encoder.transform(data)
print(enc_data1)
#[0 3 2 1 3 2]

#ถ้าจะแปลงข้อมูลครั้งต่อไป (หากเป็นชุดเดียวกัน) ให้เรียกเมธอด transform() ได้เลย
enc_data2 = encoder.transform(['Mango', 'Durian', 'Durian'])
print(enc_data2)
#[3 1 1]

enc_data3 = encoder.transform(['Grape', 'Mango', 'Mango', 'Durian'])
print(enc_data3)
#[2 3 3 1]

enc_data4 = encoder.transform(['mango', 'Mangosteen', 'Melon'])  #Error
#เกิดข้อผิดพลาด เพราะ
#mango เขียนด้วยตัวพิมพ์ที่ไม่ตรงกับข้อมูลที่กำหนดให้แก่ fit()
#Mangosteen และ Melon ไม่มีอยู่ในข้อมูลที่กำหนดให้แก่ fit()

[0 3 2 1 3 2]
[3 1 1]
[2 3 3 1]


In [ ]:
#standard scaler

from sklearn.preprocessing import StandardScaler

data = [[2, 2000],
        [3.5, 5500],
        [1.75, 2150],
        [3.14, 4130],
        [2.25, 2564]]

scaler = StandardScaler()
scaler.fit(data)
data2 = scaler.transform(data)
print(data2)
print()

data_test = [[1.23, 3210]]
print(scaler.transform(data_test))

[[-0.78178395 -0.9416242 ]
 [ 1.43919317  1.65585743]
 [-1.1519468  -0.83030356]
 [ 0.90615866  0.63912891]
 [-0.41162109 -0.52305859]]

[[-1.92188553 -0.04363769]]


In [ ]:
#train_test_split (1)

from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split

x, y = make_classification(n_samples=10, n_features=4, 
                           n_classes=2, random_state=0)

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=0)

print(x_train)
print(y_train)
print()
print(x_test)
print(y_test)


[[-0.0568887   1.20960511 -0.98740462  0.99958558]
 [-0.04621249  1.48755048 -1.19536732  1.27804656]
 [-0.14778398 -0.52978546  0.29484027 -0.79249401]
 [-0.7187573   2.14171734 -2.24080141  0.50054121]
 [-0.66261566  2.37124104 -2.3748206   0.82768797]
 [-0.01669425 -0.84862223  0.6476239  -0.81753611]
 [ 1.46552373 -1.56101351  2.38363567  1.56914464]]
[1 1 0 0 0 0 1]

[[-0.80328386  1.23271508 -1.60020786 -0.51203824]
 [ 1.00732222 -0.91817318  1.51783379  1.22140561]
 [-0.06642482  1.77341402 -1.43411205  1.50037656]]
[0 1 1]
